### PR TITLE
Tdd

### PR DESCRIPTION
**Pull request by sogh**

### CODE REVIEW

**Comment by Phezygg** [comment]
Ok I cant figure out where the user inputs their commands.

**Comment by sogh** [comment]
> k I cant figure out where the user inputs their commands.

This line in MyGame.Run() :

            self.input_queue.append(input("Enter command: "))

**Comment by Phezygg** [comment]
So when the game is first run it checks Step() to see what it returns.  Since this is the initial startup the input_queue is empty so the input interpreter assigns a value of ' ' to cmd, this causes the if statement to fall all the way to the else and return ' is not a valid command' each time you start.  Maybe a special case for startup to avoid this?

**Comment by sogh** [comment]
> So when the game is first run it checks Step() to see what it returns. Since this is the initial startup the input_queue is empty so the input interpreter assigns a value of ' ' to cmd, this causes the if statement to fall all the way to the else and return ' is not a valid command' each time you start. Maybe a special case for startup to avoid this?

Good point good point. 
I'm thinking instead of an 'if first time' style check, I will initialize the command queue with a 'do nothing' command.

**Comment by sogh** [comment]
Actually, even better I just indented over all the input handling under the check
if len(self.input_queue) > 0:

also moved the render text calls down since I found a bug where the position displayed was lagging behind the true position.

**Pull request merged**
